#ifndef MONITORCOMMAND
#define MONITORCOMMAND

#define CMD_HEARTBEAT 100 // 心跳命令
#define CMD_EXECUTECMD 101 //
#define CMD_GETFULLSCREEN 102 // 执行cmd命令
#define CMD_STARTCAPTURE 103 //
#define CMD_COMPLETECAPTURE 104
#endif // MONITORCOMMAND

